// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -source=cache.go -destination=mocks/mock_cache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockGetter is a mock of Getter interface.
type MockGetter[V any] struct {
	ctrl     *gomock.Controller
	recorder *MockGetterMockRecorder[V]
	isgomock struct{}
}

// MockGetterMockRecorder is the mock recorder for MockGetter.
type MockGetterMockRecorder[V any] struct {
	mock *MockGetter[V]
}

// NewMockGetter creates a new mock instance.
func NewMockGetter[V any](ctrl *gomock.Controller) *MockGetter[V] {
	mock := &MockGetter[V]{ctrl: ctrl}
	mock.recorder = &MockGetterMockRecorder[V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetter[V]) EXPECT() *MockGetterMockRecorder[V] {
	return m.recorder
}

// Get mocks base method.
func (m *MockGetter[V]) Get(ctx context.Context, key string) (V, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockGetterMockRecorder[V]) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGetter[V])(nil).Get), ctx, key)
}

// MockSetter is a mock of Setter interface.
type MockSetter[V any] struct {
	ctrl     *gomock.Controller
	recorder *MockSetterMockRecorder[V]
	isgomock struct{}
}

// MockSetterMockRecorder is the mock recorder for MockSetter.
type MockSetterMockRecorder[V any] struct {
	mock *MockSetter[V]
}

// NewMockSetter creates a new mock instance.
func NewMockSetter[V any](ctrl *gomock.Controller) *MockSetter[V] {
	mock := &MockSetter[V]{ctrl: ctrl}
	mock.recorder = &MockSetterMockRecorder[V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetter[V]) EXPECT() *MockSetterMockRecorder[V] {
	return m.recorder
}

// Set mocks base method.
func (m *MockSetter[V]) Set(ctx context.Context, key string, value V, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSetterMockRecorder[V]) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSetter[V])(nil).Set), ctx, key, value, ttl)
}

// MockDeleter is a mock of Deleter interface.
type MockDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockDeleterMockRecorder
	isgomock struct{}
}

// MockDeleterMockRecorder is the mock recorder for MockDeleter.
type MockDeleterMockRecorder struct {
	mock *MockDeleter
}

// NewMockDeleter creates a new mock instance.
func NewMockDeleter(ctrl *gomock.Controller) *MockDeleter {
	mock := &MockDeleter{ctrl: ctrl}
	mock.recorder = &MockDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleter) EXPECT() *MockDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeleter) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeleterMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeleter)(nil).Delete), ctx, key)
}

// MockCache is a mock of Cache interface.
type MockCache[V any] struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder[V]
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder[V any] struct {
	mock *MockCache[V]
}

// NewMockCache creates a new mock instance.
func NewMockCache[V any](ctrl *gomock.Controller) *MockCache[V] {
	mock := &MockCache[V]{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder[V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache[V]) EXPECT() *MockCacheMockRecorder[V] {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCache[V]) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheMockRecorder[V]) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCache[V])(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockCache[V]) Get(ctx context.Context, key string) (V, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder[V]) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache[V])(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockCache[V]) Set(ctx context.Context, key string, value V, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder[V]) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache[V])(nil).Set), ctx, key, value, ttl)
}
